UPSTREAM: soc: amlogic: meson-clk-measure: Add missing REGMAP_MMIO dependency
This patchs adds a missing dependency on REGMAP_MMIO.
This cause the following build failure on SPARC:
drivers/soc/amlogic/meson-clk-measure.o: In function `meson_msr_probe':
meson-clk-measure.c:(.text+0xc4): undefined reference to `__devm_regmap_init_mmio_clk'

Signed-off-by: Corentin Labbe <clabbe@baylibre.com>
Signed-off-by: Kevin Hilman <khilman@baylibre.com>
(cherry picked from commit f56c06271c1c3caef9c7ef200e3d89967fd98a8e)
Signed-off-by: Neil Armstrong <narmstrong@baylibre.com>

Change-Id: Ic679289adc4112e766d24d24e8250aff142b6ac7